import { SOURCES, type SeedSite } from "./types";

export const AMERICAS: SeedSite[] = [
  {
    name: "Ashburn — Data Center Alley",
    lat: 39.0438,
    lng: -77.4874,
    approxCount: 120,
    operator: "Equinix, Digital Realty, AWS, and others",
    notes:
      "Loudoun County, Virginia. The densest concentration of datacenters on Earth — a large share of global internet traffic passes through this one county.",
    sourceUrl:
      "https://en.wikipedia.org/wiki/Data_center#Northern_Virginia",
  },
  {
    name: "Boydton",
    lat: 36.6676,
    lng: -78.3875,
    approxCount: 12,
    operator: "Microsoft",
    notes: "Microsoft's East US Azure anchor campus in southern Virginia.",
    sourceUrl: SOURCES.microsoft,
  },
  {
    name: "Umatilla / Boardman",
    lat: 45.9174,
    lng: -119.3428,
    approxCount: 10,
    operator: "AWS",
    notes: "Oregon campus behind the us-west-2 region.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "The Dalles",
    lat: 45.5946,
    lng: -121.1787,
    approxCount: 5,
    operator: "Google",
    notes:
      "Google's first purpose-built datacenter, sited on the Columbia River for cheap hydroelectric power.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Prineville",
    lat: 44.3001,
    lng: -120.8345,
    approxCount: 10,
    operator: "Meta",
    notes:
      "Meta's first owned datacenter and the birthplace of the Open Compute Project.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "Council Bluffs",
    lat: 41.2619,
    lng: -95.8608,
    approxCount: 6,
    operator: "Google",
    notes: "One of Google's largest campuses by investment, in Iowa.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Quincy",
    lat: 47.2343,
    lng: -119.8526,
    approxCount: 9,
    operator: "Microsoft",
    notes:
      "Central Washington campus drawing on Columbia Basin hydro power.",
    sourceUrl: SOURCES.microsoft,
  },
  {
    name: "Mount Pleasant",
    lat: 42.7183,
    lng: -87.9126,
    approxCount: 6,
    operator: "Microsoft",
    notes:
      "Wisconsin AI campus built on the site originally announced for a Foxconn plant.",
    sourceUrl: SOURCES.microsoft,
  },
  {
    name: "Memphis — Colossus",
    lat: 35.0662,
    lng: -90.152,
    approxCount: 2,
    operator: "xAI",
    notes:
      "Converted appliance factory in Boxtown housing one of the largest GPU training clusters ever assembled. Controversial locally over its on-site gas turbines.",
    sourceUrl: "https://en.wikipedia.org/wiki/Colossus_(supercomputer)",
  },
  {
    name: "Abilene — Stargate",
    lat: 32.4487,
    lng: -99.7331,
    approxCount: 8,
    operator: "Oracle / OpenAI / Crusoe",
    notes:
      "Texas flagship of the Stargate AI infrastructure programme; built out as a multi-gigawatt training campus.",
    sourceUrl: "https://en.wikipedia.org/wiki/Stargate_LLC",
  },
  {
    name: "New Albany",
    lat: 40.0812,
    lng: -82.8088,
    approxCount: 14,
    operator: "Meta, Google, AWS",
    notes:
      "Ohio's fastest-growing datacenter cluster, north-east of Columbus.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "Altoona",
    lat: 41.6444,
    lng: -93.4649,
    approxCount: 5,
    operator: "Meta",
    notes: "Meta's Des Moines-area Iowa campus.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "Papillion / Sarpy County",
    lat: 41.1544,
    lng: -96.0422,
    approxCount: 6,
    operator: "Meta, Google",
    notes: "Nebraska cluster south of Omaha, shared by several hyperscalers.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "Lenoir",
    lat: 35.914,
    lng: -81.539,
    approxCount: 4,
    operator: "Google",
    notes: "North Carolina campus built on a former furniture-plant site.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Forest City",
    lat: 35.3343,
    lng: -81.8648,
    approxCount: 4,
    operator: "Meta",
    notes: "Rutherford County, North Carolina.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "Maiden",
    lat: 35.5732,
    lng: -81.1737,
    approxCount: 3,
    operator: "Apple",
    notes: "Apple's North Carolina iCloud campus with large on-site solar.",
    sourceUrl: SOURCES.apple,
  },
  {
    name: "Douglas County",
    lat: 33.6895,
    lng: -84.7477,
    approxCount: 4,
    operator: "Google",
    notes: "Google's Georgia campus, west of Atlanta.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Berkeley County",
    lat: 33.0632,
    lng: -80.0334,
    approxCount: 4,
    operator: "Google",
    notes: "Moncks Corner, South Carolina.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Clarksville",
    lat: 36.5298,
    lng: -87.3595,
    approxCount: 3,
    operator: "Google",
    notes: "Montgomery County, Tennessee.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Gallatin",
    lat: 36.3884,
    lng: -86.4467,
    approxCount: 3,
    operator: "Meta",
    notes: "Meta's Tennessee campus, north-east of Nashville.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "Huntsville",
    lat: 34.7304,
    lng: -86.5861,
    approxCount: 3,
    operator: "Meta",
    notes: "North Alabama campus.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "Pryor Creek",
    lat: 36.3084,
    lng: -95.3169,
    approxCount: 3,
    operator: "Google",
    notes: "Mayes County, Oklahoma, on the MidAmerica Industrial Park.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Goodyear / Phoenix West",
    lat: 33.4353,
    lng: -112.3576,
    approxCount: 8,
    operator: "Microsoft",
    notes:
      "Arizona campus notable for the water demands of cooling in a desert metro.",
    sourceUrl: SOURCES.microsoft,
  },
  {
    name: "Mesa",
    lat: 33.4152,
    lng: -111.8315,
    approxCount: 10,
    operator: "Google, Meta, EdgeCore",
    notes: "East-valley Phoenix cluster.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Eagle Mountain",
    lat: 40.3141,
    lng: -112.0069,
    approxCount: 4,
    operator: "Meta",
    notes: "Utah County campus south-west of Salt Lake City.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "Cheyenne",
    lat: 41.14,
    lng: -104.8202,
    approxCount: 6,
    operator: "Microsoft, Meta",
    notes: "Wyoming cluster, wind-powered and cold-climate cooled.",
    sourceUrl: SOURCES.microsoft,
  },
  {
    name: "Henderson",
    lat: 36.0395,
    lng: -114.9817,
    approxCount: 3,
    operator: "Google",
    notes: "Nevada campus in the Las Vegas metro.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Santa Clara",
    lat: 37.3541,
    lng: -121.9552,
    approxCount: 55,
    operator: "Equinix, Digital Realty, and others",
    notes:
      "Silicon Valley's colocation core — small buildings, extreme density, very expensive power.",
    sourceUrl:
      "https://en.wikipedia.org/wiki/Data_center#Silicon_Valley",
  },
  {
    name: "Elk Grove Village",
    lat: 41.995,
    lng: -87.9703,
    approxCount: 25,
    operator: "Digital Realty, Equinix, CyrusOne",
    notes: "Chicago's primary datacenter cluster, near O'Hare.",
    sourceUrl: "https://en.wikipedia.org/wiki/Elk_Grove_Village,_Illinois",
  },
  {
    name: "Dallas–Fort Worth",
    lat: 32.7767,
    lng: -96.797,
    approxCount: 30,
    operator: "Meta, Digital Realty, and others",
    notes: "Large and fast-growing North Texas cluster.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "San Antonio",
    lat: 29.4241,
    lng: -98.4936,
    approxCount: 10,
    operator: "Microsoft, Meta",
    notes: "South Texas campus cluster.",
    sourceUrl: SOURCES.microsoft,
  },
  {
    name: "Bonner Springs / Kansas City",
    lat: 39.0619,
    lng: -94.8819,
    approxCount: 3,
    operator: "Meta",
    notes: "Meta's Kansas campus.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "Rosemount",
    lat: 44.7394,
    lng: -93.1258,
    approxCount: 2,
    operator: "Meta",
    notes: "Minnesota campus south of the Twin Cities.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "Hillsboro",
    lat: 45.5229,
    lng: -122.9898,
    approxCount: 12,
    operator: "Digital Realty, QTS, and others",
    notes:
      "Oregon landing point for several trans-Pacific submarine cables.",
    sourceUrl: "https://en.wikipedia.org/wiki/Hillsboro,_Oregon",
  },
  {
    name: "Toronto",
    lat: 43.6532,
    lng: -79.3832,
    approxCount: 12,
    operator: "AWS, Microsoft, Google, Equinix",
    notes: "Canada's largest cloud region cluster.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Montréal",
    lat: 45.5017,
    lng: -73.5673,
    approxCount: 10,
    operator: "AWS, OVHcloud, Google",
    notes: "Cheap hydroelectric power and a cold climate.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "São Paulo",
    lat: -23.5505,
    lng: -46.6333,
    approxCount: 14,
    operator: "AWS, Microsoft, Google, Ascenty",
    notes: "South America's primary cloud hub.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Querétaro",
    lat: 20.5888,
    lng: -100.3899,
    approxCount: 8,
    operator: "Microsoft, Google, Odata",
    notes: "Mexico's main datacenter corridor.",
    sourceUrl: SOURCES.microsoft,
  },
  {
    name: "Santiago",
    lat: -33.4489,
    lng: -70.6693,
    approxCount: 4,
    operator: "Google, AWS",
    notes: "Chile's cloud cluster; Google's Quilicura campus sits here.",
    sourceUrl: SOURCES.google,
  },
];
