import { SOURCES, type SeedSite } from "./types";

export const ASIA_PACIFIC: SeedSite[] = [
  {
    name: "Singapore",
    lat: 1.3521,
    lng: 103.8198,
    approxCount: 28,
    operator: "AWS, Google, Microsoft, Equinix, ST Telemedia",
    notes:
      "South-east Asia's hub. The government froze new datacenter construction from 2019 to 2022 over land, power and water limits.",
    sourceUrl: "https://en.wikipedia.org/wiki/Data_center",
  },
  {
    name: "Jurong West",
    lat: 1.3404,
    lng: 103.709,
    approxCount: 3,
    operator: "Google",
    notes: "Google's Singapore campus in the western industrial belt.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Mumbai",
    lat: 19.076,
    lng: 72.8777,
    approxCount: 22,
    operator: "AWS, Microsoft, Google, Yotta, CtrlS",
    notes:
      "India's largest cluster and the landing point for most of the country's submarine cables.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Hyderabad",
    lat: 17.385,
    lng: 78.4867,
    approxCount: 12,
    operator: "Microsoft, Google, CtrlS",
    notes:
      "Site of Microsoft's largest datacenter investment in India; a fast-growing second Indian hub.",
    sourceUrl: SOURCES.microsoft,
  },
  {
    name: "Chennai",
    lat: 13.0827,
    lng: 80.2707,
    approxCount: 10,
    operator: "AWS, STT, Sify",
    notes:
      "Second Indian cable landing hub; AWS's ap-south-2 region anchors here.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Pune",
    lat: 18.5204,
    lng: 73.8567,
    approxCount: 6,
    operator: "AWS, NTT, Nxtra",
    notes: "Availability-zone overflow for the Mumbai region.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Noida / Delhi NCR",
    lat: 28.5355,
    lng: 77.391,
    approxCount: 8,
    operator: "Yotta, Nxtra, STT",
    notes: "Northern India's main cluster, serving the Delhi capital region.",
    sourceUrl: "https://en.wikipedia.org/wiki/Data_center",
  },
  {
    name: "Inzai / Tokyo",
    lat: 35.8317,
    lng: 140.1453,
    approxCount: 20,
    operator: "AWS, Google, NTT, Equinix",
    notes:
      "Chiba prefecture's Inzai corridor carries much of the Tokyo region's capacity.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Osaka",
    lat: 34.6937,
    lng: 135.5023,
    approxCount: 12,
    operator: "AWS, Microsoft, Google",
    notes: "Japan's disaster-recovery counterpart region to Tokyo.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Changhua County",
    lat: 24.0518,
    lng: 120.5161,
    approxCount: 3,
    operator: "Google",
    notes: "Google's Taiwan campus, its first in Asia.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Seoul",
    lat: 37.5665,
    lng: 126.978,
    approxCount: 16,
    operator: "AWS, Microsoft, Google, Naver",
    notes: "South Korea's cluster, concentrated in the capital region.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Hong Kong",
    lat: 22.3193,
    lng: 114.1694,
    approxCount: 14,
    operator: "Equinix, Global Switch, AWS",
    notes: "Long-standing East Asian interconnection hub.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Sydney",
    lat: -33.8688,
    lng: 151.2093,
    approxCount: 20,
    operator: "AWS, Microsoft, Google, NextDC",
    notes: "Australia's primary cluster.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Melbourne",
    lat: -37.8136,
    lng: 144.9631,
    approxCount: 12,
    operator: "AWS, Microsoft, NextDC",
    notes: "Australia's second region.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Jakarta",
    lat: -6.2088,
    lng: 106.8456,
    approxCount: 10,
    operator: "AWS, Google, Microsoft, DCI",
    notes: "Indonesia's cloud hub and the fastest-growing in the region.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Johor Bahru",
    lat: 1.4927,
    lng: 103.7414,
    approxCount: 12,
    operator: "Microsoft, Google, YTL, Bridge",
    notes:
      "Malaysian border region absorbing the build-out Singapore's moratorium pushed across the strait.",
    sourceUrl: SOURCES.microsoft,
  },
];

export const MIDDLE_EAST_AFRICA: SeedSite[] = [
  {
    name: "Dubai",
    lat: 25.2048,
    lng: 55.2708,
    approxCount: 12,
    operator: "AWS, Microsoft, Equinix, Khazna",
    notes: "The Gulf's primary cloud and interconnection hub.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Abu Dhabi",
    lat: 24.4539,
    lng: 54.3773,
    approxCount: 8,
    operator: "G42 / Khazna, Microsoft",
    notes:
      "Centre of the UAE's national AI compute programme, including the Stargate UAE build-out.",
    sourceUrl: SOURCES.microsoft,
  },
  {
    name: "Doha",
    lat: 25.2854,
    lng: 51.531,
    approxCount: 5,
    operator: "Google, Microsoft, Ooredoo",
    notes: "Qatar's cloud region.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Tel Aviv",
    lat: 32.0853,
    lng: 34.7818,
    approxCount: 8,
    operator: "AWS, Google, Microsoft",
    notes: "Israel's cloud cluster, including the Nimbus government region.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Johannesburg",
    lat: -26.2041,
    lng: 28.0473,
    approxCount: 10,
    operator: "AWS, Microsoft, Teraco",
    notes:
      "Africa's largest cluster; Teraco's campus is the continent's main interconnection point.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Cape Town",
    lat: -33.9249,
    lng: 18.4241,
    approxCount: 6,
    operator: "AWS, Teraco",
    notes: "AWS's af-south-1 region and a submarine cable landing point.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Lagos",
    lat: 6.5244,
    lng: 3.3792,
    approxCount: 5,
    operator: "MainOne, Equinix, Rack Centre",
    notes: "West Africa's main interconnection hub.",
    sourceUrl: "https://en.wikipedia.org/wiki/Data_center",
  },
  {
    name: "Nairobi",
    lat: -1.2921,
    lng: 36.8219,
    approxCount: 4,
    operator: "Microsoft, iColo, Africa Data Centres",
    notes: "East Africa's cloud cluster.",
    sourceUrl: SOURCES.microsoft,
  },
];
