import { SOURCES, type SeedSite } from "./types";

export const EUROPE: SeedSite[] = [
  {
    name: "Dublin",
    lat: 53.3498,
    lng: -6.2603,
    approxCount: 35,
    operator: "AWS, Microsoft, Google, Equinix",
    notes:
      "Europe's densest cluster. Datacenters consume such a large share of Irish grid capacity that EirGrid paused new connections in the region.",
    sourceUrl: "https://en.wikipedia.org/wiki/Data_centres_in_Ireland",
  },
  {
    name: "Clonee",
    lat: 53.4153,
    lng: -6.4372,
    approxCount: 4,
    operator: "Meta",
    notes: "Meta's County Meath campus, west of Dublin.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "Slough / West London",
    lat: 51.5085,
    lng: -0.595,
    approxCount: 30,
    operator: "Equinix, Virtus, Ark, Microsoft",
    notes:
      "The UK's primary datacenter corridor, along the M4 west of Heathrow.",
    sourceUrl: "https://en.wikipedia.org/wiki/Slough_Trading_Estate",
  },
  {
    name: "Frankfurt",
    lat: 50.1109,
    lng: 8.6821,
    approxCount: 45,
    operator: "Equinix, Digital Realty, NTT, and others",
    notes:
      "Home of DE-CIX, one of the largest internet exchange points in the world.",
    sourceUrl: "https://en.wikipedia.org/wiki/DE-CIX",
  },
  {
    name: "Amsterdam",
    lat: 52.3676,
    lng: 4.9041,
    approxCount: 32,
    operator: "Equinix, Digital Realty, Switch",
    notes:
      "AMS-IX exchange point; the municipality imposed a moratorium on new builds in 2019 over power and land pressure.",
    sourceUrl: "https://en.wikipedia.org/wiki/AMS-IX",
  },
  {
    name: "Middenmeer / Hollands Kroon",
    lat: 52.8117,
    lng: 5.0142,
    approxCount: 5,
    operator: "Microsoft",
    notes: "North Holland hyperscale campus on reclaimed polder land.",
    sourceUrl: SOURCES.microsoft,
  },
  {
    name: "Eemshaven",
    lat: 53.4386,
    lng: 6.8317,
    approxCount: 4,
    operator: "Google",
    notes:
      "Groningen coastal campus, sited next to offshore wind landing points.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Saint-Ghislain",
    lat: 50.4527,
    lng: 3.8181,
    approxCount: 4,
    operator: "Google",
    notes:
      "Google's Belgian campus — the first to run entirely without mechanical chillers.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Hamina",
    lat: 60.5693,
    lng: 27.1878,
    approxCount: 3,
    operator: "Google",
    notes:
      "Converted Finnish paper mill cooled with seawater from the Gulf of Finland; waste heat feeds the local district heating network.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Luleå",
    lat: 65.5848,
    lng: 22.1567,
    approxCount: 3,
    operator: "Meta",
    notes:
      "Just below the Arctic Circle — cooled largely by outside air, powered by Nordic hydro.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "Odense",
    lat: 55.3617,
    lng: 10.3808,
    approxCount: 3,
    operator: "Meta",
    notes: "Danish campus that exports waste heat to the city's heating grid.",
    sourceUrl: SOURCES.meta,
  },
  {
    name: "Fredericia",
    lat: 55.5657,
    lng: 9.7527,
    approxCount: 2,
    operator: "Google",
    notes: "Google's Denmark campus in Jutland.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Skien",
    lat: 59.2096,
    lng: 9.609,
    approxCount: 2,
    operator: "Google",
    notes: "Norwegian campus at Gromstul, powered by hydroelectricity.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Paris",
    lat: 48.8566,
    lng: 2.3522,
    approxCount: 25,
    operator: "Equinix, Data4, Scaleway, AWS",
    notes: "France's main cluster, concentrated in the northern suburbs.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Marseille",
    lat: 43.2965,
    lng: 5.3698,
    approxCount: 8,
    operator: "Digital Realty, Interxion",
    notes:
      "Mediterranean submarine-cable landing hub linking Europe to Africa, Asia and the Middle East.",
    sourceUrl: "https://en.wikipedia.org/wiki/Submarine_communications_cable",
  },
  {
    name: "Madrid",
    lat: 40.4168,
    lng: -3.7038,
    approxCount: 14,
    operator: "AWS, Microsoft, Google, Equinix",
    notes: "Iberia's fastest-growing cloud cluster.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Milan",
    lat: 45.4642,
    lng: 9.19,
    approxCount: 12,
    operator: "AWS, Microsoft, Aruba",
    notes: "Italy's primary cloud region.",
    sourceUrl: SOURCES.aws,
  },
  {
    name: "Zürich",
    lat: 47.3769,
    lng: 8.5417,
    approxCount: 10,
    operator: "Google, Microsoft, Green",
    notes:
      "Switzerland's cluster; Google's largest engineering site outside the US is also here.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Warsaw",
    lat: 52.2297,
    lng: 21.0122,
    approxCount: 8,
    operator: "Google, Microsoft, Atman",
    notes: "Central Europe's main cloud region.",
    sourceUrl: SOURCES.google,
  },
  {
    name: "Stockholm",
    lat: 59.3293,
    lng: 18.0686,
    approxCount: 10,
    operator: "AWS, Microsoft, EcoDataCenter",
    notes: "Nordic cloud region with district-heating waste-heat recovery.",
    sourceUrl: SOURCES.aws,
  },
];
